from enum import Enum


class ConciliationTask(Enum):
    UPDATE_REPORT_STATUS = "Actualizando estatus del reporte"
    S3_TO_REDIS = "Extrayendo de S3 a Redis"
    VALIDATE_DATA = "Validando datos del archivo"
    APLLY_OPERATIONS = "Aplicando operaciones"
    APPLY_FILTERS = "Aplicando filtros"
    UNIFIED_DATA = "Unificando datos"
    PIPELINE_MULTISOURCE = "Pipeline multisource"
    GET_PIVOTE = "Obteniendo pivote del archivo"
    VALIDATE_PIVOTE = "Validando pivote del archivo"
    LIST_PIVOTE = "Listando pivotes del archivo"
    GET_SAT_DATA = "Obteniendo datos del SAT"
    CONCILIATION = "Conciliando datos del ERP con el SAT"
    GET_PENDING_METADATA = "Obteniendo metadatos de pendientes"
    CALCULATE_OPERATIONS = "Calculando operaciones"
    GET_SAT_NO_ERP = "Obteniendo datos del SAT sin ERP"
    GET_SAT_FISCAL_DATA = "Obteniendo datos fiscales del SAT sin UUID/FOLIO/SERIE-FOLIO"
    GET_SHEETS = "Obteniendo reportes extras del SAT"
    VALIDATE_PROJECT_TYPE = "Validando tipo de proyecto para el reporte"
    ETIQUETTE = "Etiquetando datos"
    GENERATE_HEADERS = "Generando headers"
    GENERATE_REPORT = "Generando reporte"
    RESUMEN_SHEETS = "Generando hojas resumen"
    ERP_SAT_SHEET = "Generando resumen de datos ERP-SAT"
    SAT_NO_ERP_SHEET = "Generando resumen de datos SAT no ERP"
    EXTRA_SHEETS = "Generando hojas extras"
    METADATA_SHEETS = "Generando hojas de metadatos"
    PIVOT_TABLE_SHEETS = "Generando tablas dinámicas"
    PIVOT_TABLES_FORMAT = "Generando formato de tablas dinámicas"
    RESUMEN_INDICADORES = "Generando resumen de indicadores"
    SAVE_REPORT = "Guardando reporte"
